version: '3'
services:
  auth:
    environment:
      - HOST=$HOST
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/auth/
    ports:
     - '5000:5000'
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "petnet_auth_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "9999:5432"
